package pioneer.com.Entity;
// Generated 2016-2-20 10:42:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PClickmoods generated by hbm2java
 */
public class PClickmoods{

	private Integer CId;
	private int MId;
	private String UIdList;
	private Integer browsedTimes;
	private Integer praisedTimes;
	private String comment;
	private Date clickdate;
	private PMoods moods;
	public PClickmoods() {
	}

	public PClickmoods(int MId, String comment, Date clickdate) {
		this.MId = MId;
		this.comment = comment;
		this.clickdate = clickdate;
	}
	
	public Integer getCId() {
		return this.CId;
	}

	public void setCId(Integer CId) {
		this.CId = CId;
	}

	public int getMId() {
		return this.MId;
	}

	public void setMId(int MId) {
		this.MId = MId;
	}

	public Integer getBrowsedTimes() {
		return this.browsedTimes;
	}

	public void setBrowsedTimes(Integer browsedTimes) {
		this.browsedTimes = browsedTimes;
	}

	public Integer getPraisedTimes() {
		return this.praisedTimes;
	}

	public void setPraisedTimes(Integer praisedTimes) {
		this.praisedTimes = praisedTimes;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getClickdate() {
		return this.clickdate;
	}

	public void setClickdate(Date clickdate) {
		this.clickdate = clickdate;
	}

	 

	public PMoods getMoods() {
		return moods;
	}

	public void setMoods(PMoods moods) {
		this.moods = moods;
	}

	public String getUIdList() {
		return UIdList;
	}

	public void setUIdList(String uIdList) {
		UIdList = uIdList;
	}

}
