package pioneer.com.Entity;
// Generated 2016-2-20 10:42:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PMessage generated by hbm2java
 */
public class PMessage implements java.io.Serializable {

	private Integer msgid;
	private Integer fromUid;
	private Integer toUid;
	private String content;
	private Date createTime;

	public PMessage() {
	}

	public PMessage(String content, Date createTime) {
		this.content = content;
		this.createTime = createTime;
	}

	public PMessage(Integer fromUid, Integer toUid, String content, Date createTime) {
		this.fromUid = fromUid;
		this.toUid = toUid;
		this.content = content;
		this.createTime = createTime;
	}

	public Integer getMsgid() {
		return this.msgid;
	}

	public void setMsgid(Integer msgid) {
		this.msgid = msgid;
	}

	public Integer getFromUid() {
		return this.fromUid;
	}

	public void setFromUid(Integer fromUid) {
		this.fromUid = fromUid;
	}

	public Integer getToUid() {
		return this.toUid;
	}

	public void setToUid(Integer toUid) {
		this.toUid = toUid;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
