package pioneer.com.Entity;
// Generated 2016-2-20 10:42:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PMoods generated by hbm2java
 */
public class PMoods implements java.io.Serializable {

	private Integer MId;
	private int FUid;
	private String mcontent;
	private Date createdTime;
	private Integer isPublic;
	private PClickmoods moodsinfo;
	public PMoods() {
	}

	public PMoods(int FUid, String mcontent, Date createdTime) {
		this.FUid = FUid;
		this.mcontent = mcontent;
		this.createdTime = createdTime;
	}

	public PMoods(int FUid, String mcontent, Date createdTime, Integer isPublic) {
		this.FUid = FUid;
		this.mcontent = mcontent;
		this.createdTime = createdTime;
		this.isPublic = isPublic;
	}

	public Integer getMId() {
		return this.MId;
	}

	public void setMId(Integer MId) {
		this.MId = MId;
	}

	public int getFUid() {
		return this.FUid;
	}

	public void setFUid(int FUid) {
		this.FUid = FUid;
	}

	public String getMcontent() {
		return this.mcontent;
	}

	public void setMcontent(String mcontent) {
		this.mcontent = mcontent;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Integer getIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(Integer isPublic) {
		this.isPublic = isPublic;
	}

	public PClickmoods getMoodsinfo() {
		return moodsinfo;
	}

	public void setMoodsinfo(PClickmoods moodsinfo) {
		this.moodsinfo = moodsinfo;
	}

}
