package pioneer.com.Entity;
// Generated 2016-2-20 10:42:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PUsers generated by hbm2java
 */
public class PUsers implements java.io.Serializable {

	private Integer UId;
	private String username;
	private String email;
	private Date dateJoined;

	public PUsers() {
	}

	public PUsers(String username, String email, Date dateJoined) {
		this.username = username;
		this.email = email;
		this.dateJoined = dateJoined;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getDateJoined() {
		return this.dateJoined;
	}

	public void setDateJoined(Date dateJoined) {
		this.dateJoined = dateJoined;
	}

}
