package pioneer.com.Entity;
// Generated 2016-2-3 12:08:39 by Hibernate Tools 4.3.1.Final

/**
 * UserDemoskins generated by hbm2java
 */
public class UserDemoskins {

	private Integer sid;
	private String sname;
	private String scontent;
	private Integer pid;

	public UserDemoskins() {
	}

	public UserDemoskins(String sname, String scontent) {
		this.sname = sname;
		this.scontent = scontent;
	}

	public UserDemoskins(String sname, String scontent, Integer pid) {
		this.sname = sname;
		this.scontent = scontent;
		this.pid = pid;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getScontent() {
		return this.scontent;
	}

	public void setScontent(String scontent) {
		this.scontent = scontent;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

}
