package pioneer.com.Entity;
// Generated 2016-1-23 23:00:50 by Hibernate Tools 3.4.0.CR1

/**
 * Users generated by hbm2java
 */
public class Users{

	private int id;
	private String username;
	private String pwd;
	private String email;
	private String qq;

	public Users() {
	}

	public Users(int id) {
		this.id = id;
	}

	public Users(int id, String username, String pwd, String email, String qq) {
		this.id = id;
		this.username = username;
		this.pwd = pwd;
		this.email = email;
		this.qq = qq;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

}
