package pioneer.com.Entity;
// Generated 2016-2-3 12:08:39 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * UserProfile generated by hbm2java
 */
public class UserProfile   {

	private Integer pid;
	private String pname;
	private int psex;
	private Date pregtime;
	private String pip;
	private String phomesite;
	private int uid;

	public UserProfile() {
	}

	public UserProfile(String pname, int psex, Date pregtime, String pip, String phomesite, int uid) {
		this.pname = pname;
		this.psex = psex;
		this.pregtime = pregtime;
		this.pip = pip;
		this.phomesite = phomesite;
		this.uid = uid;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public int getPsex() {
		return this.psex;
	}

	public void setPsex(int psex) {
		this.psex = psex;
	}

	public Date getPregtime() {
		return this.pregtime;
	}

	public void setPregtime(Date pregtime) {
		this.pregtime = pregtime;
	}

	public String getPip() {
		return this.pip;
	}

	public void setPip(String pip) {
		this.pip = pip;
	}

	public String getPhomesite() {
		return this.phomesite;
	}

	public void setPhomesite(String phomesite) {
		this.phomesite = phomesite;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

}
