package pioneer.com.Entity;
// Generated 2016-2-3 12:08:39 by Hibernate Tools 4.3.1.Final

/**
 * Users generated by hbm2java
 */
public class Users  {

	private int id;
	private String username;
	private String pwd;
	private String email;

	public Users() {
	}

	public Users(int id) {
		this.id = id;
	}

	public Users(int id, String username, String pwd, String email) {
		this.id = id;
		this.username = username;
		this.pwd = pwd;
		this.email = email;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
