package pioneer.com.Entity;
// Generated 2016-2-3 12:08:39 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * UserMood generated by hbm2java
 */
public class UserMood {

	private Integer mid;
	private String mcontent;
	private String mpictureUrl;
	private Integer mpraisedTimes;
	private Date createdTime;
	private Integer browsedTimes;
	private int uid;

	public UserMood() {
	}

	public UserMood(String mcontent, String mpictureUrl, Date createdTime, int uid) {
		this.mcontent = mcontent;
		this.mpictureUrl = mpictureUrl;
		this.createdTime = createdTime;
		this.uid = uid;
	}

	public UserMood(String mcontent, String mpictureUrl, Integer mpraisedTimes, Date createdTime, Integer browsedTimes,
			int uid) {
		this.mcontent = mcontent;
		this.mpictureUrl = mpictureUrl;
		this.mpraisedTimes = mpraisedTimes;
		this.createdTime = createdTime;
		this.browsedTimes = browsedTimes;
		this.uid = uid;
	}

	public Integer getMid() {
		return this.mid;
	}

	public void setMid(Integer mid) {
		this.mid = mid;
	}

	public String getMcontent() {
		return this.mcontent;
	}

	public void setMcontent(String mcontent) {
		this.mcontent = mcontent;
	}

	public String getMpictureUrl() {
		return this.mpictureUrl;
	}

	public void setMpictureUrl(String mpictureUrl) {
		this.mpictureUrl = mpictureUrl;
	}

	public Integer getMpraisedTimes() {
		return this.mpraisedTimes;
	}

	public void setMpraisedTimes(Integer mpraisedTimes) {
		this.mpraisedTimes = mpraisedTimes;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Integer getBrowsedTimes() {
		return this.browsedTimes;
	}

	public void setBrowsedTimes(Integer browsedTimes) {
		this.browsedTimes = browsedTimes;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

}
