package pioneer.com.Entity;
// Generated 2016-2-3 12:08:39 by Hibernate Tools 4.3.1.Final

/**
 * UserAlbums generated by hbm2java
 */
public class UserAlbums implements java.io.Serializable {

	private Integer aid;
	private Integer cateId;
	private Integer browsedTime;
	private Integer browsedTimes;
	private int quoteUid;
	private String quotePhoneUrl;

	public UserAlbums() {
	}

	public UserAlbums(int quoteUid, String quotePhoneUrl) {
		this.quoteUid = quoteUid;
		this.quotePhoneUrl = quotePhoneUrl;
	}

	public UserAlbums(Integer cateId, Integer browsedTime, Integer browsedTimes, int quoteUid, String quotePhoneUrl) {
		this.cateId = cateId;
		this.browsedTime = browsedTime;
		this.browsedTimes = browsedTimes;
		this.quoteUid = quoteUid;
		this.quotePhoneUrl = quotePhoneUrl;
	}

	public Integer getAid() {
		return this.aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	public Integer getCateId() {
		return this.cateId;
	}

	public void setCateId(Integer cateId) {
		this.cateId = cateId;
	}

	public Integer getBrowsedTime() {
		return this.browsedTime;
	}

	public void setBrowsedTime(Integer browsedTime) {
		this.browsedTime = browsedTime;
	}

	public Integer getBrowsedTimes() {
		return this.browsedTimes;
	}

	public void setBrowsedTimes(Integer browsedTimes) {
		this.browsedTimes = browsedTimes;
	}

	public int getQuoteUid() {
		return this.quoteUid;
	}

	public void setQuoteUid(int quoteUid) {
		this.quoteUid = quoteUid;
	}

	public String getQuotePhoneUrl() {
		return this.quotePhoneUrl;
	}

	public void setQuotePhoneUrl(String quotePhoneUrl) {
		this.quotePhoneUrl = quotePhoneUrl;
	}

}
