package pioneer.com.Entity;
// Generated 2016-2-3 12:08:39 by Hibernate Tools 4.3.1.Final

/**
 * UserCommentrecord generated by hbm2java
 */
public class UserCommentrecord implements java.io.Serializable {

	private Integer cid;
	private String ccotent;
	private int commentedUid;

	public UserCommentrecord() {
	}

	public UserCommentrecord(int commentedUid) {
		this.commentedUid = commentedUid;
	}

	public UserCommentrecord(String ccotent, int commentedUid) {
		this.ccotent = ccotent;
		this.commentedUid = commentedUid;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public String getCcotent() {
		return this.ccotent;
	}

	public void setCcotent(String ccotent) {
		this.ccotent = ccotent;
	}

	public int getCommentedUid() {
		return this.commentedUid;
	}

	public void setCommentedUid(int commentedUid) {
		this.commentedUid = commentedUid;
	}

}
