package pioneer.com.Entity;
import java.util.Date;

/**
 * UserDailyrecord generated by hbm2java
 */
public class UserDailyrecord implements java.io.Serializable {

	private Integer rid;
	private Date createdTime;
	private String title;
	private String content;
	private Integer browsedTime;
	private Integer praisedTime;
	private String commentContent;
	private int uid;

	public UserDailyrecord() {
	}

	public UserDailyrecord(Date createdTime, String title, String content, String commentContent, int uid) {
		this.createdTime = createdTime;
		this.title = title;
		this.content = content;
		this.commentContent = commentContent;
		this.uid = uid;
	}

	public UserDailyrecord(Date createdTime, String title, String content, Integer browsedTime, Integer praisedTime,
			String commentContent, int uid) {
		this.createdTime = createdTime;
		this.title = title;
		this.content = content;
		this.browsedTime = browsedTime;
		this.praisedTime = praisedTime;
		this.commentContent = commentContent;
		this.uid = uid;
	}

	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getBrowsedTime() {
		return this.browsedTime;
	}

	public void setBrowsedTime(Integer browsedTime) {
		this.browsedTime = browsedTime;
	}

	public Integer getPraisedTime() {
		return this.praisedTime;
	}

	public void setPraisedTime(Integer praisedTime) {
		this.praisedTime = praisedTime;
	}

	public String getCommentContent() {
		return this.commentContent;
	}

	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

}
