package pioneer.com.Entity;
// Generated 2016-2-3 12:08:39 by Hibernate Tools 4.3.1.Final

/**
 * UserAlbumsCategory generated by hbm2java
 */
public class UserAlbumsCategory implements java.io.Serializable {

	private Integer cateid;
	private String catename;
	private String catesite;

	public UserAlbumsCategory() {
	}

	public UserAlbumsCategory(String catename, String catesite) {
		this.catename = catename;
		this.catesite = catesite;
	}

	public Integer getCateid() {
		return this.cateid;
	}

	public void setCateid(Integer cateid) {
		this.cateid = cateid;
	}

	public String getCatename() {
		return this.catename;
	}

	public void setCatename(String catename) {
		this.catename = catename;
	}

	public String getCatesite() {
		return this.catesite;
	}

	public void setCatesite(String catesite) {
		this.catesite = catesite;
	}

}
